services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebVision\WvDeepltranslate\:
    resource: '../Classes/*'

  WebVision\WvDeepltranslate\Hooks\TranslateHook:
    public: true

  WebVision\WvDeepltranslate\Service\DeeplService:
    arguments:
      $cache: '@cache.wvdeepltranslate'

  WebVision\WvDeepltranslate\Listener\ModifyPageLayoutContent:
    tags:
      - name: event.listener
        identifier: 'wvdeepltranslate-ModifyPageLayoutContent'

  cache.wvdeepltranslate:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'wvdeepltranslate' ]
